### ISSUE TITLE
Praesentation

### ISSUE THREAD

**Issue by henrikgh** [henrikgh/BV_Zusatzinhalte#1]
kannst du die sachen bitten in einen seperaten Ordner packen, sonst wird das schnell unuebersichtlich.

**Comment by Buechta** [comment]
kann ich auch machen, wenn ich die Präsentation für das aktuelle Projekt hochlade.

**Comment by henrikgh** [comment]
so, hab die eben mal umkopiert.
falls du ne andere Struktur haben moechtest kannst du das ja einfach aendern
